### ISSUE TITLE
ChatChat Not Working in 1.21 (Error on message send)

### ISSUE THREAD

**Issue by UPSOKen** [HelpChat/ChatChat#234]
Updated my server to 1.21, and when I send a message I can see it in the console, but the in-game chat remains blank. It also prints this error:

`[17:07:14 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatChat v1.0.0-SNAPSHOT-74
java.util.regex.PatternSyntaxException: Illegal repetition near index 13
@CraftPlayer{name=Lecraeman}
             ^
        at java.base/java.util.regex.Pattern.error(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.closure(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.sequence(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.expr(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.<init>(Unknown Source) ~[?:?]
        at java.base/java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at ChatChat.jar/at.helpch.chatchat.util.MentionUtils.lambda$replaceMention$1(MentionUtils.java:60) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.libs.net.kyori.adventure.builder.AbstractBuilder.configureAndBuild(AbstractBuilder.java:52) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.libs.net.kyori.adventure.text.Component.replaceText(Component.java:2430) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.util.MentionUtils.replaceMention(MentionUtils.java:59) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.util.MentionUtils.replaceMention(MentionUtils.java:87) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.util.MentionUtils.processPersonalMentions(MentionUtils.java:132) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.mention.PersonalMention.processMention(PersonalMention.java:50) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.mention.MentionManagerImpl.processMentions(MentionManagerImpl.java:51) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.util.MessageProcessor.process(MessageProcessor.java:191) ~[ChatChat.jar:?]
        at ChatChat.jar/at.helpch.chatchat.listener.ChatListener.onChat(ChatListener.java:104) ~[ChatChat.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor342.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-DEV-6327fac]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2338) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2454) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2110) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[lightspigot-1.21.jar:1.21-DEV-6327fac]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by UPSOKen** [comment]
I am a fool, shortly after posting this I realized I was one dev snapshot behind, and it works fine on snapshot 75 (I was on 74).
