### ISSUE TITLE
Plugin strips colour added to messages by other plugins

### ISSUE THREAD

**Issue by Xemorr** [HelpChat/ChatChat#93]
I have a plugin that edits the message before ChatChat formats it, but it just strips the colour.

I attempted to rewrite it using Paper's AsyncChatEvent and Adventure Components, and that is fully incompatible.

**Comment by BlitzOffline** [comment]
Yeah. We remove legacy colors and formats from messages. That is because [MiniMessage](https://docs.adventure.kyori.net/minimessage/) doesn't support legacy and would just throw an error. We instead recommend people use PlaceholderAPI placeholders inside the format itself not the message. This way they can use the [Kyorify](https://api.extendedclip.com/expansions/kyorify/) expansion which will translate the legacy colors to MiniMessage tags. We might add our own version of the kyorify expansion inside the plugin itself but until then, this is the best option.

**Comment by BlitzOffline** [comment]
> Yeah I get that but it makes custom parsing harder, PlaceholderAPI isn't exactly what I am trying to achieve as PlaceholderAPI enforces the % either side. I want to be able to just parse any old text. I'm now using your ChatChatEvent but it doesn't seem to be called.

That must be a bug then. We are calling ChatChatEvent in code as far as I'm aware. I'll have to test this later and let you know.

**Comment by Xemorr** [comment]
It could just be user error on my half but I'm not sure what I've messed up if it is. I am depending on the API rather than your plugin if that makes any difference.

**Comment by BlitzOffline** [comment]
> It could just be user error on my half but I'm not sure what I've messed up if it is. I am depending on the API rather than your plugin if that makes any difference.

It should work. Just make sure you are not relocating the API inside your code.

**Comment by Xemorr** [comment]
```
[20:02:15 ERROR]: Could not pass event ChatChatEvent to ESEmoji v2.0-SNAPSHOT
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component at.helpch.chatchat.api.event.ChatChatEvent.message()'
	at me.xemor.esemoji.feature.EmojiChatChat.onChat(EmojiChatChat.java:20) ~[original-ESEmoji-2.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor135.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at at.helpch.chatchat.util.MessageProcessor.process(MessageProcessor.java:78) ~[ChatChat-1.0-SNAPSHOT.jar:?]
	at at.helpch.chatchat.listener.ChatListener.onChat(ChatListener.java:79) ~[ChatChat-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor111.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:195) ~[purpur-1.19.jar:git-Purpur-1732]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:67) ~[purpur-1.19.jar:git-Purpur-1732]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2384) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$21(ServerGamePacketListenerImpl.java:2313) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java:2313) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2210) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Any help?
