### ISSUE TITLE
NoSuchMethodError - adventure components in ChatChatEvent 

### ISSUE THREAD

**Issue by Xemorr** [HelpChat/ChatChat#94]
```
[20:02:15 ERROR]: Could not pass event ChatChatEvent to ESEmoji v2.0-SNAPSHOT
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component at.helpch.chatchat.api.event.ChatChatEvent.message()'
	at me.xemor.esemoji.feature.EmojiChatChat.onChat(EmojiChatChat.java:20) ~[original-ESEmoji-2.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor135.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at at.helpch.chatchat.util.MessageProcessor.process(MessageProcessor.java:78) ~[ChatChat-1.0-SNAPSHOT.jar:?]
	at at.helpch.chatchat.listener.ChatListener.onChat(ChatListener.java:79) ~[ChatChat-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor111.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:195) ~[purpur-1.19.jar:git-Purpur-1732]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:67) ~[purpur-1.19.jar:git-Purpur-1732]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2384) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$21(ServerGamePacketListenerImpl.java:2313) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java:2313) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2210) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Any help? oh I know what the issue will be, it'll be due to the relocation in your build script, it thinks it's a different type of component to the one I have. I built ChatChat using gradle plugin:shadowJar

**Comment by BlitzOffline** [comment]
Its not related to the different component. Rather it seems like a method from the ChatChatEvent is missing. Make sure you're using the latest version of ChatChat on your server and also make sure you're not shading the API inside your plugin.

**Comment by Xemorr** [comment]
I am quite sure it is, I am not shading the API inside my plugin. 
![image](https://user-images.githubusercontent.com/31805746/181655369-8f2f55ac-3b82-46f1-b492-54acef0ef5cd.png)
If you look at this screenshot from Recaf, you can see at the top your relocated import of Component class, and this relocated Component being used within the API.

**Comment by Xemorr** [comment]
I have not got a clue why, but you're shading essentials into your jar by default. When I removed the relocation for adventure (what does adventure have to do with essentials? does it use it now?) it broke essentials and all plugins depending on essentials. Switched essentials to compileOnly to fix that.

**Comment by Kqliber** [comment]
merging to main branch automatically closed this issue. but I've went ahead and set essentials to compileOnly. not sure why it was in the first place, just an honest mistake!

if thats all there is to fix the issue, let me know and ill close this again

**Comment by Xemorr** [comment]
Well, the thing that fixed my main issue was disabling relocation of adventure. That allowed me to use the library. I just also stumbled across the shading of essentials on my travels fixing that haha. idk if disabling relocation of adventure is the best move though

**Comment by BlitzOffline** [comment]
@Xemorr do you still have issues with this? I was going thru issues and I've noticed this was not marked as fixed yet. If this is not a problem using the latest version of ChatChat, please let us know so we can close this.

Also by any chance, did you maybe import the wrong Component? You need to make sure you import the ChatChat Component. otherwise it will throw errors like that. My guess is that you did something like:

```java
import net.kyori.adventure.text.Component;

final Component message = event.message();
```

but you actually are supposed to import:
```java
import at.helpch.chatchat.libs.net.kyori.adventure.text.Component;
```

**Comment by Xemorr** [comment]
If I import at.helpch.chatchat.libs.... that would make it incompatible with my own versions of that Component so I'd have to make some way of converting, although I agree it would probably fix the issue. I just fixed it for my personal use by disabling your relocation.

**Comment by BlitzOffline** [comment]
> If I import at.helpch.chatchat.libs.... that would make it incompatible with my own versions of that Component so I'd have to make some way of converting, although I agree it would probably fix the issue. I just fixed it for my personal use by disabling your relocation.

Yeah that is 100% the problem then. The components are incompatible. You can however import both of them but you should note that you cannot pass your own components to ChatChat. you'll have to provide a chatchat component. You can also access MiniMessage from ChatChat if you want to create a ChatChat component. I will be closing the issue now.
